Repository uclouvain/osis, pull requests merged in 2019-05, with the labels that each got.

#5369 OSIS-2567 correct translation
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
Labels: learning_unit

#5376 [QA] Add partnership app in service
  webservices/urls.py
Labels: patch

#5393 [PATCH] Add STAFF_FUNDING_URL to base.py for partenrship
  backoffice/settings/base.py
Labels: patch

#5406 [QA] Osis 2943
  base/business/education_groups/general_information_sections.py
Labels: patch

#5402 OSIS-2901 adapt form for external learning unit
  base/forms/learning_unit/external_learning_unit.py
  base/forms/learning_unit/learning_unit_create.py
  base/templates/learning_unit/blocks/components.html
  base/templates/learning_unit/blocks/form/form_external.html
  base/templates/learning_unit/blocks/institution.html
  base/templates/learning_unit/blocks/partim_attributes.html
  base/templates/learning_unit/external/update.html
  base/templates/learning_unit/learning_unit_layout.html
  base/tests/factories/organization.py
  base/tests/forms/test_external_learning_unit.py
  base/tests/views/learning_units/external/test_update.py
  base/tests/views/test_organization.py
  base/views/learning_units/update.py
  base/views/organization.py
Labels: learning_unit

#5437 OSIS-2961-2962 update col to add proposition and update icon
  base/templates/learning_unit/by_activity.html
  base/templates/learning_unit/by_external.html
Labels: learning_unit

#5438 OSIS-2963-2965 update col to add modification and update icon
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
  base/templates/blocks/span/span_mod_status.html
  base/templates/learning_unit/summary_list.html
Labels: learning_unit

#5439 OSIS-2964 add filter for status in search form LU
  base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html
  base/templates/learning_unit/blocks/form/search_form_summary_list.html
Labels: learning_unit

#5446 OSIS-2965 debug color
  base/templates/learning_unit/summary_list.html
Labels: learning_unit

#5449 fixed translation of header in xls scores file
  assessments/locale/fr_BE/LC_MESSAGES/django.po
Labels: patch

#5447 OSIS-2965 change logo for inactive
  base/templates/learning_unit/by_activity.html
  base/templates/learning_unit/by_external.html
  base/templates/learning_unit/summary_list.html
Labels: learning_unit

#5462 Osis 2591 Correction de bug pour les valeurs par défaut des form OF
  base/fixtures/validation_rules.csv
  base/forms/education_group/training.py
  base/migrations/0453_auto_20190515_1109.py
  base/models/validation_rule.py
  base/templates/education_group/blocks/form/group.html
  base/templates/education_group/blocks/form/minitraining.html
Labels: WIP

#5463 OSIS-2960 add warning when Q and vol not in same time
  base/business/learning_unit.py
  base/business/learning_units/quadrimester_strategy.py
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
  base/models/learning_component_year.py
  base/tests/models/test_learning_unit_year.py
  base/views/learning_units/detail.py
Labels: learning_unit

#5488 OSIS-2960 add 'NoStrategy' + test
  base/business/learning_units/quadrimester_strategy.py
  base/models/learning_component_year.py
  base/tests/models/test_learning_unit_year.py
Labels: learning_unit

#5496 [QA] OSIS-3027 : Display english texts to special admisssion condition of …
  base/templates/education_group/tab_admission_conditions.html
Labels: patch

#5502 Release 0.50.5
  base/templates/education_group/tab_admission_conditions.html
  webservices/tests/test_ws_catalog_offer.py
  webservices/views.py
Labels: patch

#5506 OSIS-3029 update translation
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
Labels: learning_unit

#5503 OSIS-2457 Ajouter l'icone de status des informations pédagogique
  base/templates/blocks/span/span_mod_status.html
  base/templates/learning_unit/summary_list.html
Labels: patch

#5504 OSIS-2881 Display tutor function in description fiche
  attribution/models/attribution.py
  base/locale/fr_BE/LC_MESSAGES/django.po
  base/templates/learning_unit/blocks/panel/educational_informations.html
  base/templates/learning_unit/blocks/summary_locked.html
  base/views/learning_units/pedagogy/read.py
Labels: patch

#5525 OSIS-3030 update report
  base/migrations/0457_message_template_egys_automatic_postponement_update.py
  base/models/education_group_year.py
  base/tests/models/test_education_group_year.py
  base/utils/send_mail.py
Labels: education_group

#5516 Osis 3021
  assessments/business/score_encoding_export.py
  assessments/templates/online_encoding.html
  assessments/templates/online_encoding_form.html
Labels: patch

#5529 OSIS-3030 debug translation
  base/migrations/0457_message_template_egys_automatic_postponement_update.py
  base/models/education_group_year.py
  base/tests/models/test_education_group_year.py
Labels: education_group

#5507 OSIS-2952 generalization of icons in learning units lists display
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
  base/templates/blocks/span/span_mod_status.html
  base/templates/learning_unit/blocks/form/search_form_external_learning_unit.html
  base/templates/learning_unit/blocks/form/search_form_summary_list.html
  base/templates/learning_unit/by_activity.html
  base/templates/learning_unit/by_external.html
  base/templates/learning_unit/summary_list.html
Labels: patch

#5530 OSIS-3050 removed distinct('tutor') from attributions display (for summary and scores responsibles)
  assessments/views/scores_responsible.py
  attribution/business/summary_responsible.py
  attribution/models/attribution.py
  attribution/tests/business/test_summary_responsible.py
  attribution/tests/models/test_attribution.py
  attribution/views/summary_responsible.py
Labels: patch

#5539 OSIS-2952 change logo for inactive UEs
  base/templates/learning_unit/by_activity.html
  base/templates/learning_unit/by_external.html
  base/templates/learning_unit/summary_list.html
  base/views/learning_units/educational_information.py
Labels: patch

#5542 OSIS-3030 template for automatic postponement to N+6
  base/migrations/0457_message_template_egys_automatic_postponement_update.py
  base/tests/utils/test_send_mail.py
  base/utils/send_mail.py
Labels: education_group

#5545 OSIS-3052 Fixed bug when edit attributs To Test
  base/business/education_groups/group_element_year_tree.py
  base/business/group_element_years/attach.py
  base/forms/education_group/group_element_year.py
Labels: patch
