Repository uclouvain/osis, pull requests merged in 2019-07, with the labels that each got.

#5738 OSIS-2976 add check on valid (partial_)acronym
  base/locale/en/LC_MESSAGES/django.po
  base/locale/fr_BE/LC_MESSAGES/django.po
  base/models/education_group_year.py
  base/tests/factories/education_group_year.py
  base/tests/models/test_education_group_year.py
  base/tests/views/group_element_years/test_edit.py
  base/tests/views/learning_units/test_formations_tab.py
  requirements.txt
Labels: WIP

#5773 [TO QA] OSIS-3174 Ensure that during repartition external_ids of Attribution …
  base/tests/views/learning_units/test_charge_repartition.py
  base/views/learning_units/charge_repartition.py
Labels: patch

#5780 OSIS-3185 keep tab when nav in tree
  base/business/education_groups/group_element_year_tree.py
  base/tests/business/education_groups/test_build_tree.py
  base/tests/views/education_groups/test_detail.py
  base/tests/views/test_education_group.py
  base/views/education_groups/detail.py
Labels: education_group

#5806 OSIS-3217 debug warning show twice
  assessments/templates/scores_encoding_by_learning_unit.html
Labels: score-encoding

#5838 [To QA] OSIS-3242 fixed perm to update certificate aims if EducationGroup.year equals to working year
  base/templatetags/education_group.py
  base/tests/views/education_groups/test_update.py
  base/views/education_groups/update.py
Labels: patch

#5846 [QA] OSIS-3242 prevent from updating an EducationGroup before 2019
  base/templatetags/education_group.py
  base/views/education_groups/update.py
Labels: patch

#5847 [QA] OSIS-3241 : Add faculties even if attached to UCL or a sector
  base/models/person.py
  base/tests/models/test_entity_version.py
Labels: patch

#5883 [QA] OSIS-3273 protect academic calendar to superuser
  base/tests/views/test_academic_calendar.py
  base/views/academic_calendar.py
Labels: patch, urgent
